name: Docker Image CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  SH8: $(echo ${GITHUB_SHA} | cut -c1-8)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Get short commit
      run: |
        echo "SH8=$(echo ${{ env.SH8 }})" >> $GITHUB_ENV
    
    - name: Docker Login - Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
    
    - name: Build e Push no Azure Container Registry
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/tooglestoreweb:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/tooglestoreweb:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/tooglestoreweb:${{ env.SH8 }}
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/tooglestoreweb
    
    - name: Logando no Azure para Deployment
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure WebApp Container - Deployment da Aplicacao
      uses: Azure/webapps-container-deploy@v2
      with:
        app-name: aguiartogglestore
        images: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/tooglestoreweb:latest
